name: CI

on:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: backend
            dir: backend
            pyfile: backend/.python-version
          - name: detection
            dir: detection
            pyfile: detection/.python-version

    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install just
        uses: extractions/setup-just@v3
        with:
          just-version: '1.26.0'
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version-file: ${{ matrix.pyfile }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Setup venv
        run: uv sync --locked --all-extras --dev
      - name: Lint
        run: just lint
